### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by reilgun** [LagPixelLOL/qlora#2]
I originally opened this issue in https://github.com/artidoro/qlora but I've since realized I can only reproduce it on your fork.
The original version from atinoda works just fine, though it's missing flash attention.

Any idea what could be causing this error?
My configuration is as follows: https://raw.githubusercontent.com/reilgun/runpod-qlora-trainer/master/scripts/run_flash_large.sh
```
Loading checkpoint shards: 100%|██████████| 3/3 [00:29<00:00,  9.95s/it]
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Downloading (…)neration_config.json: 100%|██████████| 182/182 [00:00<00:00, 812kB/s]
/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py:640: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Downloading (…)okenizer_config.json: 100%|██████████| 855/855 [00:00<00:00, 4.05MB/s]
Downloading tokenizer.model: 100%|██████████| 500k/500k [00:00<00:00, 12.1MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 438/438 [00:00<00:00, 1.99MB/s]
Adding special tokens.
Traceback (most recent call last):
  File "/workspace/qlora/flash_qlora.py", line 6, in <module>
    train()
  File "/workspace/qlora/qlora.py", line 707, in train
    model, tokenizer = get_accelerate_model(args, checkpoint_dir)
  File "/workspace/qlora/qlora.py", line 372, in get_accelerate_model
    "unk_token": tokenizer.convert_ids_to_tokens(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    for index in ids:
TypeError: 'NoneType' object is not iterable
```

This seems to happen with spicyboros-13b-2.2, but not with say, the original llama13b base model. However I'd been able to finetune on airoboros-13B-2.1 just fine previously using this fork. Not sure what's going wrong here.
Something with the special token settings?

**Comment by reilgun** [comment]
It appears that `model.config.pad_token_id` is None which causes the error. Looking in the tokenizer config for this model I can't find anything weird.
But when loaded this is what the dict contains
```
LlamaConfig {
  "_name_or_path": "jondurbin/spicyboros-13b-2.2",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 40,
  "pretraining_tp": 1,
  "quantization_config": {
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.33.2",
  "use_cache": false,
  "vocab_size": 32000
}

```
The model files do define the unk token.
For base 13B, the config dict looks like this
```
LlamaConfig {
  "_name_or_path": "/TheBloke_Llama-2-13B-fp16",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "num_key_value_heads": 40,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "quantization_config": {
    "bnb_4bit_compute_dtype": "bfloat16",
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_use_double_quant": true,
    "llm_int8_enable_fp32_cpu_offload": false,
    "llm_int8_has_fp16_weight": false,
    "llm_int8_skip_modules": null,
    "llm_int8_threshold": 6.0,
    "load_in_4bit": true,
    "load_in_8bit": false,
    "quant_method": "bitsandbytes"
  },
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.33.2",
  "use_cache": true,
  "vocab_size": 32001
}
```

**Comment by reilgun** [comment]
Assuming the correct pad_token_id really is 0, this is an easy fix:
```Python
"unk_token": tokenizer.convert_ids_to_tokens(
    model.config.pad_token_id if (model.config.pad_token_id != -1 and model.config.pad_token_id != None) else tokenizer.pad_token_id
),
```
This works. But the question is, why is this only happening for me using this fork?

**Comment by reilgun** [comment]
I made a PR. Given I don't know the root cause of why the pad_token_id remains unset, I don't know if you should merge it. But checking for its absence seems sensible enough in any case, I think the behaviour in this PR is better than just checking against it being -1 as it did before.

**Comment by LagPixelLOL** [comment]
Oops only seen it right now since my email is flooded xD.

**Comment by LagPixelLOL** [comment]
merged
